[colors.cursor]
cursor = "0xffffff"

[colors.primary]
background = "#050505"

[cursor.style]
blinking = "On"

[font]
size = 14

[font.normal]
family = "JetBrainsMonoNerdFontMono"

[window]
opacity = 0.85
