[colors.cursor]
cursor = "0xffffff"

[colors.primary]
background = "#0d1117"

[cursor.style]
blinking = "On"

[font]
size = 12

[font.normal]
family = "JetBrainsMonoNerdFontMono"

[window]
# opacity = 0.85
