do
  require 'plugins.telescope'
  require 'plugins.ui'
  require 'plugins.autocompletion'
  require 'plugins.formatter'
  require 'plugins.diagnostics'
  require 'plugins.highlighting'
  require 'plugins.lsp'
  require 'plugins.mini'
  require 'plugins.nvim-lint'
  require 'plugins.packbuild'
  require 'config.autocommands'
  require 'config.keymap'
  require 'config.options'
end
