return {
  { 'folke/todo-comments.nvim', event = 'VimEnter', dependencies = { 'nvim-lua/plenary.nvim' }, opts = { signs = false } },
  {
    'nvim-treesitter/nvim-treesitter',
    tag = 'v0.10.0',
    lazy = false,
    build = ':TSUpdate',
    opts = {
      ensure_installed = {
        'cpp',
        'bash',
        'c',
        'html',
        'javascript',
        'jsdoc',
        'jsonc',
        'json',
        'lua',
        'luadoc',
        'luap',
        'markdown',
        'markdown_inline',
        'python',
        'query',
        'regex',
        'tsx',
        'typescript',
        'vim',
        'vimdoc',
        'yaml',
        'rust',
        'toml',
        'ron',
      },
      auto_install = true,
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = { 'ruby' },
      },
      indent = { enable = true, disable = { 'ruby' } },
    },
  },
}
