[colors.cursor]
cursor = "0xffffff"

[colors.primary]
background = "#0d1117"

[cursor.style]
blinking = "On"

[font]
size = 12

[font.normal]
family = "JetBrainsMonoNerdFontMono"

[window]
option_as_alt = "OnlyLeft"
# opacity = 0.85

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
