syntax on
set regexpengine=0
filetype plugin indent on
set formatoptions-=t
set formatoptions+=croql
set path=.,**
set undofile
set undodir=~/.vim/undodir
set directory=~/.vim/swap
set number
set relativenumber
set laststatus=2
set wildmenu
set wildmode=full:lastused
set breakindent
set nohlsearch
set nocursorline
set conceallevel=0
set pumheight=0
set scrolloff=8
set expandtab
set shiftwidth=4
set softtabstop=4
set ignorecase
set smartcase
set autoindent
set clipboard=unnamed,unnamedplus
set background=dark
set termguicolors
set is hls
set splitbelow
set ttimeoutlen=10
set gdefault
set grepprg=grep\ -rn\ $*\ /dev/null
set completeopt=fuzzy,menuone,noinsert,popup
set wildoptions=fuzzy,pum
let g:netrw_liststyle=1

let &errorformat='e:\ file://%f:%l:%c\ %m,' . &errorformat . ',%-G%.%#'

let g:gruvbox_transparent_bg=1
let g:gruvbox_italicize_comments=0
let g:gruvbox_italicize_strings=0
let g:gruvbox_italic=0

colorscheme retrobox
hi Normal guibg=NONE

let g:fzf_action = {
	\ 'enter': 'tab split',
	\ 'ctrl-x': 'split',
	\ 'ctrl-v': 'vsplit' }

"  Map out leader key and disable default keys
let mapleader = ","
nnoremap <space> ,
vnoremap <space> ,
nnoremap Q <nop>
nnoremap ! :!
nnoremap <C-n> <cmd>w<cr><cmd>silent! cn<cr><cmd>cc<cr>
nnoremap <C-p> <cmd>w<cr><cmd>silent! cp<cr><cmd>cc<cr>
nnoremap ]q <cmd>copen 30<CR>
nnoremap [q <cmd>cclose<CR>
nnoremap <leader>sr <cmd>bro old!<CR>
vnoremap <leader>cu y:vim "<C-f>pa" src/**<C-c>
vnoremap * y/<C-f>p<CR>
vnoremap # y?<C-f>p<CR>

nnoremap <esc> <cmd>nohl<CR>
nnoremap <leader>t :!tmux split-window -v<CR><CR>
nnoremap <leader>T :!tmux split-window -h<CR><CR>
nnoremap <leader>w <C-w>
nnoremap <C-l> <C-w>l
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <leader>e <cmd>Ex<CR>

"  Center Screen after searching
"  Center screen after moving up and down
" nnoremap <C-d> <C-d>zz
" nnoremap <C-u> <C-u>zz

" nnoremap n nzzzv
" nnoremap N Nzzzv
  
nnoremap <leader><space> <cmd>w<CR><cmd>e #<CR>
nnoremap <leader>. @:

function! NetrwMapping()
endfunction

augroup netrw_mapping
  autocmd!
  autocmd filetype netrw call NetrwMapping()
augroup END

function! NetrwMapping()
  nmap <buffer> <space> <CR>
  nmap <buffer> P <C-w>z
endfunction
