syntax on
set path=.,,**
set relativenumber
set laststatus=2
set wildmenu
set wildmode=full:lastused
set breakindent
set nohlsearch
set nocursorline
set conceallevel=0
set pumheight=0
set scrolloff=8
set expandtab
set shiftwidth=4
set smartindent
set autoindent
set clipboard=unnamed,unnamedplus
set background=dark
set termguicolors
set is hls
set splitbelow
set ttimeoutlen=10
set gdefault
let g:gruvbox_transparent_bg=1
let g:gruvbox_italicize_comments=0
let g:gruvbox_italicize_strings=0
let g:gruvbox_italic=0
colorscheme gruvbox
hi Normal guibg=NONE

let g:fzf_action = {
	\ 'enter': 'tab split',
	\ 'ctrl-x': 'split',
	\ 'ctrl-v': 'vsplit' }

"  Map out leader key and disable default keys
let mapleader = ","
nnoremap <space> <nop>
nmap Q <nop>
nmap ! :!

nmap <esc> <cmd>nohl<CR>
nmap <leader>t :!tmux split-window -v<CR><CR>
nmap <leader>T :!tmux split-window -h<CR><CR>
map <leader>w <C-w>
nmap <C-l> <C-w>l
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <leader>e <cmd>Ex<CR>

"  Move selected up and down
vmap J <cmd>m '>+1<CR>gv=gv
vmap K <cmd>m '<-2<CR>gv=gv

"  Center screen after moving up and down
nmap <C-d> <C-d>zz
nmap <C-u> <C-u>zz

"  Center Screen after searching
nmap n nzzzv
nmap N Nzzzv
  
"  Go to other buffer
nmap <leader><space> <cmd>e #<CR>

" Tabs
nmap <tab>l <cmd>tabnext<CR>
nmap <tab>h <cmd>tabprevious<CR>
nmap <tab>n <cmd>tab split<CR>
nmap <tab>o <cmd>tabonly<CR>

" Fzf finder
nmap <leader>sf <cmd>FZF<CR>
nmap q! q:i!<Esc> 
